### PR TITLE
json-patch is not being considered for inclusion any more

### PR DESCRIPTION
**Pull request by tpo**
... for whatever reason: https://github.com/ansible/ansible/pull/52931#issuecomment-543801696 unless someone want to fight with "we"/upstream/RedHat/or someone there.

:-( !

### CODE REVIEW

**Comment by djmattyg007** [comment]
Hello @particledecay (and anyone else who has contributed to this module, such as @tpo). I just wanted to leave you a short message of support after coming across this.

Three and a half years ago, I submitted my own PR to ansible for a `jsonmod` module. It used a fairly primitive syntax that wasn't as powerful as JSON Patch, but I don't think I was aware of it at the time. It seemed reasonably powerful and I was quite proud of it at the time:

https://github.com/ansible/ansible/pull/20064

Unfortunately I received a similar treatment to you on #52931. After following up on it for a while, facing off absurdly off-topic messages, I gave up trying. Like you found, it wound up being a pointless waste of time for something that was increasingly unlikely to be accepted.

I've officially given up on my attempt, and am happy to see that someone has come along to make something far better (and almost certainly more reliable) than what I came up with. I'm sorry you had to go through a significant waste of time like that.

**Comment by particledecay** [comment]
@djmattyg007 hey, thanks for the support! Sorry to hear you had a similar experience. In any case, I still use Ansible a lot (as do many others), so I'm trying not to let the *people* behind it negatively influence my desire to get this functionality in *somewhere*!

I would love to have someone else help out with this module since I'm only one person and I'm pretty busy these days. I have [another PR](https://github.com/ansible-collections/community.general/pull/378) for inclusion into the community.general collection. They've been a little more amenable over there :smile:

**Comment by tpo** [comment]
Hi @particledecay,

> I would love to have someone else help out with this module since I'm only one person and I'm pretty busy these days.

I felt your (justified) sideways peek. I have told you elsewhere that I could help but currently I am unable to do so - sorry :-(

**Comment by particledecay** [comment]
@tpo nahhh, I actually wasn't "subtweeting" you there... it's OSS! I don't expect anyone to feel obligated to contribute, but if they really want to I'm open to it.

**Pull request merged**
